version: \"3.8\"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: airuae-postgres
    ports:
      - \"5432:5432\"
    environment:
      POSTGRES_USER: airuae
      POSTGRES_PASSWORD: password
      POSTGRES_DB: airuae
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airuae-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: airuae-redis
    ports:
      - \"6379:6379\"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - airuae-network
    restart: unless-stopped

networks:
  airuae-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
